config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'users#new'
  resources :sessions
  resources :tasks
  resources :users
  namespace :admin do
  	resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :phonenumber, presence: true
  validates :password_digest, presence: true
  has_many :labels, dependent: :destroy
  def self.admins
   @users = User.all
   @admins = 0
   @users.each do |user|
     if user.user_type == "admin"
       @admins += 1
     end
   end
   return @admins
 end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin_page, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == current_user.id
     redirect_to admin_users_url, notice: "You can not delete signed in user"
     @admins = User.admins
   elsif @admins == 1
     redirect_to admin_users_url, notice: "Atleast one admin must remain!"
   else
     @user.destroy
     redirect_to admin_users_url, notice: 'User was successfully destroyed.'
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fullname, :email, :phonenumber, :password, :password_confirmation)
    end
    def validate_admin_page
      unless current_user && current_user.user_type == 'admin'
        redirect_to tasks_path, notice: 'only admin can access this page'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin_page, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == current_user.id
     redirect_to admin_users_url, notice: "You can not delete signed in user"
     @admins = User.admins
   elsif @admins == 1
     redirect_to admin_users_url, notice: "Atleast one admin must remain!"
   else
     @user.destroy
     redirect_to admin_users_url, notice: 'User was successfully destroyed.'
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fullname, :email, :phonenumber, :user_type, :password, :password_confirmation)
    end

    def validate_admin_page
      unless current_user && current_user.user_type == 'admin'
        redirect_to tasks_path, notice: 'only admin can access this page'
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="main">
  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phonenumber %>
    <%= form.text_field :phonenumber %>
  </div>
  <div class="field">
    <%= form.label :user_type %>
    <%= form.text_field :user_type, disable: (true unless current_user && current_user.user_type == 'admin') %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<h1 style="text-align: center;">Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="main">
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>User_type</th>
      <th>Task number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fullname %></td>
        <td><%= user.email %></td>
        <td><%= user.phonenumber %></td>
        <td><%= user.user_type %></td>
        <td><%= user.tasks.count %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>
<div class="main">

app/views/admin/users/new.html.erb
<h1 style="text-align: center;">New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @user.phonenumber %>
</p>
<p>
  <strong>Tasks created by this user:</strong>
  <% @user.tasks.each do |task| %><br>
  <strong>Name:</strong><%= task.name %>
  <strong>Content:</strong><%= task.content %>
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>
</center>